run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - noctx
linters-settings:
  gocritic:
    enabled-tags: [diagnostic, style, performance]
